__default__:
    account: SNIC2019-3-233
    partition: largemem
    time: 60
    ntasks: 1
    cpus_per_task: 1
    job_name: '{rule}'
    output: 'logs/{rule}.%j.out'
    error: 'logs/{rule}.%j.err'

flye_assembly:
    time: 2880
    ntasks: 72

read_subsampling:
    time: 2880
